/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author lucas
 */
public class TelaLampada extends javax.swing.JFrame {

    /**
     * Creates new form TelaLampada
     */
    public TelaLampada() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrincipal = new javax.swing.JLabel();
        imgGenio = new javax.swing.JLabel();
        txtBalao = new javax.swing.JLabel();
        imgBalao = new javax.swing.JLabel();
        campoTexto = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrincipal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, 410, 30));

        imgGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio-dos-p.png"))); // NOI18N
        imgGenio.setToolTipText("");
        getContentPane().add(imgGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 184, -1));

        txtBalao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtBalao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(txtBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 120, 60));

        imgBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/85581799abacc91fc17282e66f26f73a.png"))); // NOI18N
        getContentPane().add(imgBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        campoTexto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(campoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 260, 30));

        btn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn1.setText("OK");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 70, 30));

        btn2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn2.setText("OK");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtPrincipal.setText("Vamos jogar? ");
    }//GEN-LAST:event_formWindowOpened

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        
        txtPrincipal.setText("<html>Eu sei que você quer e não vai resistir. É só digitar seu nome...</html>");
    }//GEN-LAST:event_formMouseEntered


    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
       txtPrincipal.setText("<html> E depois é só advinhar o numero que eu vou escolher entre 1 e 5...</html>"); 
    }//GEN-LAST:event_formMouseClicked

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        btn2.setVisible(false);
        String nome = campoTexto.getText();
        txtPrincipal.setText("<html>"+nome + " kkk Serio? eita nome de clandestino...</html>"); 
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLampada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLampada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLampada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLampada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLampada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JTextField campoTexto;
    private javax.swing.JLabel imgBalao;
    private javax.swing.JLabel imgGenio;
    private javax.swing.JLabel txtBalao;
    private javax.swing.JLabel txtPrincipal;
    // End of variables declaration//GEN-END:variables
}
