/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author lucas
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblBox = new javax.swing.JLabel();
        lblUm = new javax.swing.JLabel();
        selectUm = new javax.swing.JComboBox<>();
        box = new javax.swing.JLabel();
        genio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBox.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, box, org.jdesktop.beansbinding.ObjectProperty.create(), lblBox, org.jdesktop.beansbinding.BeanProperty.create("icon"));
        bindingGroup.addBinding(binding);

        getContentPane().add(lblBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, 60));

        lblUm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblUm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 30));

        selectUm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Vamos", "Não" }));
        getContentPane().add(selectUm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        box.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/85581799abacc91fc17282e66f26f73a.png"))); // NOI18N
        getContentPane().add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 330, 310));

        genio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio-dos-p.png"))); // NOI18N
        getContentPane().add(genio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 178, -1));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel box;
    private javax.swing.JLabel genio;
    private javax.swing.JLabel lblBox;
    private javax.swing.JLabel lblUm;
    private javax.swing.JComboBox<String> selectUm;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
